# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: resque-status 0.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "resque-status".freeze
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aaron Quint".freeze]
  s.date = "2023-11-27"
  s.description = "resque-status is an extension to the resque queue system that provides simple trackable jobs. It provides a Resque::Plugins::Status::Hash class which can set/get the statuses of jobs and a Resque::Plugins::Status class that when included provides easily trackable/killable jobs.".freeze
  s.email = "aaron@quirkey.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.homepage = "http://github.com/quirkey/resque-status".freeze
  s.rubygems_version = "3.1.6".freeze
  s.summary = "resque-status is an extension to the resque queue system that provides simple trackable jobs.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<resque>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
  else
    s.add_dependency(%q<resque>.freeze, ["~> 2.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
  end
end

